name: Build Blog

on:
  push:
    branches:
      - main
    paths:
      - blog-md/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Running Script
        run: |
          pip install --upgrade pip
          pip install -r auto/requirements.txt
          python blogify.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated code"
          git push
